services:
  tvtracker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tvtracker
    restart: unless-stopped
    ports:
      - "7950:8000"
    volumes:
      - /ruta/a/tu/tvtracker/data:/data
      - /ruta/a/tu/tvtracker/frontend:/app/frontend
    env_file:
      - .env
    networks:
      - TuRed

networks:
  TuRed:
    external: true
